package proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VO_Esse_Detail2.proto

public final class VO_Esse_Detail2Entity {
  private VO_Esse_Detail2Entity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VO_Esse_Detail2OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 rid = 1;
    /**
     * <code>required int32 rid = 1;</code>
     *
     * <pre>
     * 随从ID
     * </pre>
     */
    boolean hasRid();
    /**
     * <code>required int32 rid = 1;</code>
     *
     * <pre>
     * 随从ID
     * </pre>
     */
    int getRid();

    // required int32 lv = 2;
    /**
     * <code>required int32 lv = 2;</code>
     *
     * <pre>
     * 随从等级
     * </pre>
     */
    boolean hasLv();
    /**
     * <code>required int32 lv = 2;</code>
     *
     * <pre>
     * 随从等级
     * </pre>
     */
    int getLv();

    // required int64 exp = 3;
    /**
     * <code>required int64 exp = 3;</code>
     *
     * <pre>
     * 随从经验
     * </pre>
     */
    boolean hasExp();
    /**
     * <code>required int64 exp = 3;</code>
     *
     * <pre>
     * 随从经验
     * </pre>
     */
    long getExp();

    // required int32 quality = 4;
    /**
     * <code>required int32 quality = 4;</code>
     *
     * <pre>
     * 随从品质
     * </pre>
     */
    boolean hasQuality();
    /**
     * <code>required int32 quality = 4;</code>
     *
     * <pre>
     * 随从品质
     * </pre>
     */
    int getQuality();

    // required int32 throunghLv = 5;
    /**
     * <code>required int32 throunghLv = 5;</code>
     *
     * <pre>
     * 随从突破等级
     * </pre>
     */
    boolean hasThrounghLv();
    /**
     * <code>required int32 throunghLv = 5;</code>
     *
     * <pre>
     * 随从突破等级
     * </pre>
     */
    int getThrounghLv();

    // required int32 slot = 6;
    /**
     * <code>required int32 slot = 6;</code>
     *
     * <pre>
     * 装备位位置信息(10以后表示援阵暗卫位置)
     * </pre>
     */
    boolean hasSlot();
    /**
     * <code>required int32 slot = 6;</code>
     *
     * <pre>
     * 装备位位置信息(10以后表示援阵暗卫位置)
     * </pre>
     */
    int getSlot();

    // required int32 fromation = 7;
    /**
     * <code>required int32 fromation = 7;</code>
     *
     * <pre>
     * 战斗位位置信息
     * </pre>
     */
    boolean hasFromation();
    /**
     * <code>required int32 fromation = 7;</code>
     *
     * <pre>
     * 战斗位位置信息
     * </pre>
     */
    int getFromation();

    // optional bytes body = 8;
    /**
     * <code>optional bytes body = 8;</code>
     *
     * <pre>
     * 消息体
     * </pre>
     */
    boolean hasBody();
    /**
     * <code>optional bytes body = 8;</code>
     *
     * <pre>
     * 消息体
     * </pre>
     */
    com.google.protobuf.ByteString getBody();

    // repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;
    /**
     * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
     *
     * <pre>
     *技能信息
     * </pre>
     */
    java.util.List<VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2> 
        getPropsList();
    /**
     * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
     *
     * <pre>
     *技能信息
     * </pre>
     */
    VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 getProps(int index);
    /**
     * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
     *
     * <pre>
     *技能信息
     * </pre>
     */
    int getPropsCount();
    /**
     * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
     *
     * <pre>
     *技能信息
     * </pre>
     */
    java.util.List<? extends VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2OrBuilder> 
        getPropsOrBuilderList();
    /**
     * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
     *
     * <pre>
     *技能信息
     * </pre>
     */
    VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2OrBuilder getPropsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code VO_Esse_Detail2}
   */
  public static final class VO_Esse_Detail2 extends
      com.google.protobuf.GeneratedMessage
      implements VO_Esse_Detail2OrBuilder {
    // Use VO_Esse_Detail2.newBuilder() to construct.
    private VO_Esse_Detail2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VO_Esse_Detail2(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VO_Esse_Detail2 defaultInstance;
    public static VO_Esse_Detail2 getDefaultInstance() {
      return defaultInstance;
    }

    public VO_Esse_Detail2 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VO_Esse_Detail2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              rid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              lv_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              exp_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              quality_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              throunghLv_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              slot_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              fromation_ = input.readInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              body_ = input.readBytes();
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
                props_ = new java.util.ArrayList<VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2>();
                mutable_bitField0_ |= 0x00000100;
              }
              props_.add(input.readMessage(VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
          props_ = java.util.Collections.unmodifiableList(props_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VO_Esse_Detail2Entity.internal_static_VO_Esse_Detail2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VO_Esse_Detail2Entity.internal_static_VO_Esse_Detail2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VO_Esse_Detail2Entity.VO_Esse_Detail2.class, VO_Esse_Detail2Entity.VO_Esse_Detail2.Builder.class);
    }

    public static com.google.protobuf.Parser<VO_Esse_Detail2> PARSER =
        new com.google.protobuf.AbstractParser<VO_Esse_Detail2>() {
      public VO_Esse_Detail2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VO_Esse_Detail2(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VO_Esse_Detail2> getParserForType() {
      return PARSER;
    }

    public interface VO_Esse_Prop_Detail2OrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 propType = 1;
      /**
       * <code>required int32 propType = 1;</code>
       *
       * <pre>
       * 属性类型
       * </pre>
       */
      boolean hasPropType();
      /**
       * <code>required int32 propType = 1;</code>
       *
       * <pre>
       * 属性类型
       * </pre>
       */
      int getPropType();

      // required int32 propValue = 2;
      /**
       * <code>required int32 propValue = 2;</code>
       *
       * <pre>
       * 属性值
       * </pre>
       */
      boolean hasPropValue();
      /**
       * <code>required int32 propValue = 2;</code>
       *
       * <pre>
       * 属性值
       * </pre>
       */
      int getPropValue();
    }
    /**
     * Protobuf type {@code VO_Esse_Detail2.VO_Esse_Prop_Detail2}
     */
    public static final class VO_Esse_Prop_Detail2 extends
        com.google.protobuf.GeneratedMessage
        implements VO_Esse_Prop_Detail2OrBuilder {
      // Use VO_Esse_Prop_Detail2.newBuilder() to construct.
      private VO_Esse_Prop_Detail2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private VO_Esse_Prop_Detail2(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final VO_Esse_Prop_Detail2 defaultInstance;
      public static VO_Esse_Prop_Detail2 getDefaultInstance() {
        return defaultInstance;
      }

      public VO_Esse_Prop_Detail2 getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private VO_Esse_Prop_Detail2(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                propType_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                propValue_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VO_Esse_Detail2Entity.internal_static_VO_Esse_Detail2_VO_Esse_Prop_Detail2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VO_Esse_Detail2Entity.internal_static_VO_Esse_Detail2_VO_Esse_Prop_Detail2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.class, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder.class);
      }

      public static com.google.protobuf.Parser<VO_Esse_Prop_Detail2> PARSER =
          new com.google.protobuf.AbstractParser<VO_Esse_Prop_Detail2>() {
        public VO_Esse_Prop_Detail2 parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new VO_Esse_Prop_Detail2(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<VO_Esse_Prop_Detail2> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 propType = 1;
      public static final int PROPTYPE_FIELD_NUMBER = 1;
      private int propType_;
      /**
       * <code>required int32 propType = 1;</code>
       *
       * <pre>
       * 属性类型
       * </pre>
       */
      public boolean hasPropType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 propType = 1;</code>
       *
       * <pre>
       * 属性类型
       * </pre>
       */
      public int getPropType() {
        return propType_;
      }

      // required int32 propValue = 2;
      public static final int PROPVALUE_FIELD_NUMBER = 2;
      private int propValue_;
      /**
       * <code>required int32 propValue = 2;</code>
       *
       * <pre>
       * 属性值
       * </pre>
       */
      public boolean hasPropValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 propValue = 2;</code>
       *
       * <pre>
       * 属性值
       * </pre>
       */
      public int getPropValue() {
        return propValue_;
      }

      private void initFields() {
        propType_ = 0;
        propValue_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasPropType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPropValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, propType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, propValue_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, propType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, propValue_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code VO_Esse_Detail2.VO_Esse_Prop_Detail2}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2OrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return VO_Esse_Detail2Entity.internal_static_VO_Esse_Detail2_VO_Esse_Prop_Detail2_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return VO_Esse_Detail2Entity.internal_static_VO_Esse_Detail2_VO_Esse_Prop_Detail2_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.class, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder.class);
        }

        // Construct using VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          propType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          propValue_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return VO_Esse_Detail2Entity.internal_static_VO_Esse_Detail2_VO_Esse_Prop_Detail2_descriptor;
        }

        public VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 getDefaultInstanceForType() {
          return VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.getDefaultInstance();
        }

        public VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 build() {
          VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 buildPartial() {
          VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 result = new VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.propType_ = propType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.propValue_ = propValue_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2) {
            return mergeFrom((VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 other) {
          if (other == VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.getDefaultInstance()) return this;
          if (other.hasPropType()) {
            setPropType(other.getPropType());
          }
          if (other.hasPropValue()) {
            setPropValue(other.getPropValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasPropType()) {
            
            return false;
          }
          if (!hasPropValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 propType = 1;
        private int propType_ ;
        /**
         * <code>required int32 propType = 1;</code>
         *
         * <pre>
         * 属性类型
         * </pre>
         */
        public boolean hasPropType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 propType = 1;</code>
         *
         * <pre>
         * 属性类型
         * </pre>
         */
        public int getPropType() {
          return propType_;
        }
        /**
         * <code>required int32 propType = 1;</code>
         *
         * <pre>
         * 属性类型
         * </pre>
         */
        public Builder setPropType(int value) {
          bitField0_ |= 0x00000001;
          propType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 propType = 1;</code>
         *
         * <pre>
         * 属性类型
         * </pre>
         */
        public Builder clearPropType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          propType_ = 0;
          onChanged();
          return this;
        }

        // required int32 propValue = 2;
        private int propValue_ ;
        /**
         * <code>required int32 propValue = 2;</code>
         *
         * <pre>
         * 属性值
         * </pre>
         */
        public boolean hasPropValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 propValue = 2;</code>
         *
         * <pre>
         * 属性值
         * </pre>
         */
        public int getPropValue() {
          return propValue_;
        }
        /**
         * <code>required int32 propValue = 2;</code>
         *
         * <pre>
         * 属性值
         * </pre>
         */
        public Builder setPropValue(int value) {
          bitField0_ |= 0x00000002;
          propValue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 propValue = 2;</code>
         *
         * <pre>
         * 属性值
         * </pre>
         */
        public Builder clearPropValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          propValue_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:VO_Esse_Detail2.VO_Esse_Prop_Detail2)
      }

      static {
        defaultInstance = new VO_Esse_Prop_Detail2(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:VO_Esse_Detail2.VO_Esse_Prop_Detail2)
    }

    private int bitField0_;
    // required int32 rid = 1;
    public static final int RID_FIELD_NUMBER = 1;
    private int rid_;
    /**
     * <code>required int32 rid = 1;</code>
     *
     * <pre>
     * 随从ID
     * </pre>
     */
    public boolean hasRid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 rid = 1;</code>
     *
     * <pre>
     * 随从ID
     * </pre>
     */
    public int getRid() {
      return rid_;
    }

    // required int32 lv = 2;
    public static final int LV_FIELD_NUMBER = 2;
    private int lv_;
    /**
     * <code>required int32 lv = 2;</code>
     *
     * <pre>
     * 随从等级
     * </pre>
     */
    public boolean hasLv() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 lv = 2;</code>
     *
     * <pre>
     * 随从等级
     * </pre>
     */
    public int getLv() {
      return lv_;
    }

    // required int64 exp = 3;
    public static final int EXP_FIELD_NUMBER = 3;
    private long exp_;
    /**
     * <code>required int64 exp = 3;</code>
     *
     * <pre>
     * 随从经验
     * </pre>
     */
    public boolean hasExp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 exp = 3;</code>
     *
     * <pre>
     * 随从经验
     * </pre>
     */
    public long getExp() {
      return exp_;
    }

    // required int32 quality = 4;
    public static final int QUALITY_FIELD_NUMBER = 4;
    private int quality_;
    /**
     * <code>required int32 quality = 4;</code>
     *
     * <pre>
     * 随从品质
     * </pre>
     */
    public boolean hasQuality() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 quality = 4;</code>
     *
     * <pre>
     * 随从品质
     * </pre>
     */
    public int getQuality() {
      return quality_;
    }

    // required int32 throunghLv = 5;
    public static final int THROUNGHLV_FIELD_NUMBER = 5;
    private int throunghLv_;
    /**
     * <code>required int32 throunghLv = 5;</code>
     *
     * <pre>
     * 随从突破等级
     * </pre>
     */
    public boolean hasThrounghLv() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 throunghLv = 5;</code>
     *
     * <pre>
     * 随从突破等级
     * </pre>
     */
    public int getThrounghLv() {
      return throunghLv_;
    }

    // required int32 slot = 6;
    public static final int SLOT_FIELD_NUMBER = 6;
    private int slot_;
    /**
     * <code>required int32 slot = 6;</code>
     *
     * <pre>
     * 装备位位置信息(10以后表示援阵暗卫位置)
     * </pre>
     */
    public boolean hasSlot() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 slot = 6;</code>
     *
     * <pre>
     * 装备位位置信息(10以后表示援阵暗卫位置)
     * </pre>
     */
    public int getSlot() {
      return slot_;
    }

    // required int32 fromation = 7;
    public static final int FROMATION_FIELD_NUMBER = 7;
    private int fromation_;
    /**
     * <code>required int32 fromation = 7;</code>
     *
     * <pre>
     * 战斗位位置信息
     * </pre>
     */
    public boolean hasFromation() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 fromation = 7;</code>
     *
     * <pre>
     * 战斗位位置信息
     * </pre>
     */
    public int getFromation() {
      return fromation_;
    }

    // optional bytes body = 8;
    public static final int BODY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>optional bytes body = 8;</code>
     *
     * <pre>
     * 消息体
     * </pre>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes body = 8;</code>
     *
     * <pre>
     * 消息体
     * </pre>
     */
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    // repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;
    public static final int PROPS_FIELD_NUMBER = 9;
    private java.util.List<VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2> props_;
    /**
     * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
     *
     * <pre>
     *技能信息
     * </pre>
     */
    public java.util.List<VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2> getPropsList() {
      return props_;
    }
    /**
     * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
     *
     * <pre>
     *技能信息
     * </pre>
     */
    public java.util.List<? extends VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2OrBuilder> 
        getPropsOrBuilderList() {
      return props_;
    }
    /**
     * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
     *
     * <pre>
     *技能信息
     * </pre>
     */
    public int getPropsCount() {
      return props_.size();
    }
    /**
     * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
     *
     * <pre>
     *技能信息
     * </pre>
     */
    public VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 getProps(int index) {
      return props_.get(index);
    }
    /**
     * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
     *
     * <pre>
     *技能信息
     * </pre>
     */
    public VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2OrBuilder getPropsOrBuilder(
        int index) {
      return props_.get(index);
    }

    private void initFields() {
      rid_ = 0;
      lv_ = 0;
      exp_ = 0L;
      quality_ = 0;
      throunghLv_ = 0;
      slot_ = 0;
      fromation_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
      props_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasExp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuality()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasThrounghLv()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSlot()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFromation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPropsCount(); i++) {
        if (!getProps(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, lv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, exp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, quality_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, throunghLv_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, slot_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, fromation_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, body_);
      }
      for (int i = 0; i < props_.size(); i++) {
        output.writeMessage(9, props_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, rid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, lv_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, exp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, quality_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, throunghLv_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, slot_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, fromation_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, body_);
      }
      for (int i = 0; i < props_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, props_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static VO_Esse_Detail2Entity.VO_Esse_Detail2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VO_Esse_Detail2Entity.VO_Esse_Detail2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VO_Esse_Detail2Entity.VO_Esse_Detail2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VO_Esse_Detail2Entity.VO_Esse_Detail2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VO_Esse_Detail2Entity.VO_Esse_Detail2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static VO_Esse_Detail2Entity.VO_Esse_Detail2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static VO_Esse_Detail2Entity.VO_Esse_Detail2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static VO_Esse_Detail2Entity.VO_Esse_Detail2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static VO_Esse_Detail2Entity.VO_Esse_Detail2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static VO_Esse_Detail2Entity.VO_Esse_Detail2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(VO_Esse_Detail2Entity.VO_Esse_Detail2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VO_Esse_Detail2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements VO_Esse_Detail2Entity.VO_Esse_Detail2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VO_Esse_Detail2Entity.internal_static_VO_Esse_Detail2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VO_Esse_Detail2Entity.internal_static_VO_Esse_Detail2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VO_Esse_Detail2Entity.VO_Esse_Detail2.class, VO_Esse_Detail2Entity.VO_Esse_Detail2.Builder.class);
      }

      // Construct using VO_Esse_Detail2Entity.VO_Esse_Detail2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPropsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        rid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        lv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        exp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        quality_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        throunghLv_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        slot_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        fromation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        body_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (propsBuilder_ == null) {
          props_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          propsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return VO_Esse_Detail2Entity.internal_static_VO_Esse_Detail2_descriptor;
      }

      public VO_Esse_Detail2Entity.VO_Esse_Detail2 getDefaultInstanceForType() {
        return VO_Esse_Detail2Entity.VO_Esse_Detail2.getDefaultInstance();
      }

      public VO_Esse_Detail2Entity.VO_Esse_Detail2 build() {
        VO_Esse_Detail2Entity.VO_Esse_Detail2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public VO_Esse_Detail2Entity.VO_Esse_Detail2 buildPartial() {
        VO_Esse_Detail2Entity.VO_Esse_Detail2 result = new VO_Esse_Detail2Entity.VO_Esse_Detail2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.rid_ = rid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lv_ = lv_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.exp_ = exp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.quality_ = quality_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.throunghLv_ = throunghLv_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.slot_ = slot_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.fromation_ = fromation_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.body_ = body_;
        if (propsBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100)) {
            props_ = java.util.Collections.unmodifiableList(props_);
            bitField0_ = (bitField0_ & ~0x00000100);
          }
          result.props_ = props_;
        } else {
          result.props_ = propsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VO_Esse_Detail2Entity.VO_Esse_Detail2) {
          return mergeFrom((VO_Esse_Detail2Entity.VO_Esse_Detail2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VO_Esse_Detail2Entity.VO_Esse_Detail2 other) {
        if (other == VO_Esse_Detail2Entity.VO_Esse_Detail2.getDefaultInstance()) return this;
        if (other.hasRid()) {
          setRid(other.getRid());
        }
        if (other.hasLv()) {
          setLv(other.getLv());
        }
        if (other.hasExp()) {
          setExp(other.getExp());
        }
        if (other.hasQuality()) {
          setQuality(other.getQuality());
        }
        if (other.hasThrounghLv()) {
          setThrounghLv(other.getThrounghLv());
        }
        if (other.hasSlot()) {
          setSlot(other.getSlot());
        }
        if (other.hasFromation()) {
          setFromation(other.getFromation());
        }
        if (other.hasBody()) {
          setBody(other.getBody());
        }
        if (propsBuilder_ == null) {
          if (!other.props_.isEmpty()) {
            if (props_.isEmpty()) {
              props_ = other.props_;
              bitField0_ = (bitField0_ & ~0x00000100);
            } else {
              ensurePropsIsMutable();
              props_.addAll(other.props_);
            }
            onChanged();
          }
        } else {
          if (!other.props_.isEmpty()) {
            if (propsBuilder_.isEmpty()) {
              propsBuilder_.dispose();
              propsBuilder_ = null;
              props_ = other.props_;
              bitField0_ = (bitField0_ & ~0x00000100);
              propsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPropsFieldBuilder() : null;
            } else {
              propsBuilder_.addAllMessages(other.props_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRid()) {
          
          return false;
        }
        if (!hasLv()) {
          
          return false;
        }
        if (!hasExp()) {
          
          return false;
        }
        if (!hasQuality()) {
          
          return false;
        }
        if (!hasThrounghLv()) {
          
          return false;
        }
        if (!hasSlot()) {
          
          return false;
        }
        if (!hasFromation()) {
          
          return false;
        }
        for (int i = 0; i < getPropsCount(); i++) {
          if (!getProps(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        VO_Esse_Detail2Entity.VO_Esse_Detail2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (VO_Esse_Detail2Entity.VO_Esse_Detail2) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 rid = 1;
      private int rid_ ;
      /**
       * <code>required int32 rid = 1;</code>
       *
       * <pre>
       * 随从ID
       * </pre>
       */
      public boolean hasRid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 rid = 1;</code>
       *
       * <pre>
       * 随从ID
       * </pre>
       */
      public int getRid() {
        return rid_;
      }
      /**
       * <code>required int32 rid = 1;</code>
       *
       * <pre>
       * 随从ID
       * </pre>
       */
      public Builder setRid(int value) {
        bitField0_ |= 0x00000001;
        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rid = 1;</code>
       *
       * <pre>
       * 随从ID
       * </pre>
       */
      public Builder clearRid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rid_ = 0;
        onChanged();
        return this;
      }

      // required int32 lv = 2;
      private int lv_ ;
      /**
       * <code>required int32 lv = 2;</code>
       *
       * <pre>
       * 随从等级
       * </pre>
       */
      public boolean hasLv() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 lv = 2;</code>
       *
       * <pre>
       * 随从等级
       * </pre>
       */
      public int getLv() {
        return lv_;
      }
      /**
       * <code>required int32 lv = 2;</code>
       *
       * <pre>
       * 随从等级
       * </pre>
       */
      public Builder setLv(int value) {
        bitField0_ |= 0x00000002;
        lv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 lv = 2;</code>
       *
       * <pre>
       * 随从等级
       * </pre>
       */
      public Builder clearLv() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lv_ = 0;
        onChanged();
        return this;
      }

      // required int64 exp = 3;
      private long exp_ ;
      /**
       * <code>required int64 exp = 3;</code>
       *
       * <pre>
       * 随从经验
       * </pre>
       */
      public boolean hasExp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 exp = 3;</code>
       *
       * <pre>
       * 随从经验
       * </pre>
       */
      public long getExp() {
        return exp_;
      }
      /**
       * <code>required int64 exp = 3;</code>
       *
       * <pre>
       * 随从经验
       * </pre>
       */
      public Builder setExp(long value) {
        bitField0_ |= 0x00000004;
        exp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 exp = 3;</code>
       *
       * <pre>
       * 随从经验
       * </pre>
       */
      public Builder clearExp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        exp_ = 0L;
        onChanged();
        return this;
      }

      // required int32 quality = 4;
      private int quality_ ;
      /**
       * <code>required int32 quality = 4;</code>
       *
       * <pre>
       * 随从品质
       * </pre>
       */
      public boolean hasQuality() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 quality = 4;</code>
       *
       * <pre>
       * 随从品质
       * </pre>
       */
      public int getQuality() {
        return quality_;
      }
      /**
       * <code>required int32 quality = 4;</code>
       *
       * <pre>
       * 随从品质
       * </pre>
       */
      public Builder setQuality(int value) {
        bitField0_ |= 0x00000008;
        quality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 quality = 4;</code>
       *
       * <pre>
       * 随从品质
       * </pre>
       */
      public Builder clearQuality() {
        bitField0_ = (bitField0_ & ~0x00000008);
        quality_ = 0;
        onChanged();
        return this;
      }

      // required int32 throunghLv = 5;
      private int throunghLv_ ;
      /**
       * <code>required int32 throunghLv = 5;</code>
       *
       * <pre>
       * 随从突破等级
       * </pre>
       */
      public boolean hasThrounghLv() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 throunghLv = 5;</code>
       *
       * <pre>
       * 随从突破等级
       * </pre>
       */
      public int getThrounghLv() {
        return throunghLv_;
      }
      /**
       * <code>required int32 throunghLv = 5;</code>
       *
       * <pre>
       * 随从突破等级
       * </pre>
       */
      public Builder setThrounghLv(int value) {
        bitField0_ |= 0x00000010;
        throunghLv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 throunghLv = 5;</code>
       *
       * <pre>
       * 随从突破等级
       * </pre>
       */
      public Builder clearThrounghLv() {
        bitField0_ = (bitField0_ & ~0x00000010);
        throunghLv_ = 0;
        onChanged();
        return this;
      }

      // required int32 slot = 6;
      private int slot_ ;
      /**
       * <code>required int32 slot = 6;</code>
       *
       * <pre>
       * 装备位位置信息(10以后表示援阵暗卫位置)
       * </pre>
       */
      public boolean hasSlot() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 slot = 6;</code>
       *
       * <pre>
       * 装备位位置信息(10以后表示援阵暗卫位置)
       * </pre>
       */
      public int getSlot() {
        return slot_;
      }
      /**
       * <code>required int32 slot = 6;</code>
       *
       * <pre>
       * 装备位位置信息(10以后表示援阵暗卫位置)
       * </pre>
       */
      public Builder setSlot(int value) {
        bitField0_ |= 0x00000020;
        slot_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 slot = 6;</code>
       *
       * <pre>
       * 装备位位置信息(10以后表示援阵暗卫位置)
       * </pre>
       */
      public Builder clearSlot() {
        bitField0_ = (bitField0_ & ~0x00000020);
        slot_ = 0;
        onChanged();
        return this;
      }

      // required int32 fromation = 7;
      private int fromation_ ;
      /**
       * <code>required int32 fromation = 7;</code>
       *
       * <pre>
       * 战斗位位置信息
       * </pre>
       */
      public boolean hasFromation() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 fromation = 7;</code>
       *
       * <pre>
       * 战斗位位置信息
       * </pre>
       */
      public int getFromation() {
        return fromation_;
      }
      /**
       * <code>required int32 fromation = 7;</code>
       *
       * <pre>
       * 战斗位位置信息
       * </pre>
       */
      public Builder setFromation(int value) {
        bitField0_ |= 0x00000040;
        fromation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 fromation = 7;</code>
       *
       * <pre>
       * 战斗位位置信息
       * </pre>
       */
      public Builder clearFromation() {
        bitField0_ = (bitField0_ & ~0x00000040);
        fromation_ = 0;
        onChanged();
        return this;
      }

      // optional bytes body = 8;
      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes body = 8;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes body = 8;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>optional bytes body = 8;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes body = 8;</code>
       *
       * <pre>
       * 消息体
       * </pre>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000080);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }

      // repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;
      private java.util.List<VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2> props_ =
        java.util.Collections.emptyList();
      private void ensurePropsIsMutable() {
        if (!((bitField0_ & 0x00000100) == 0x00000100)) {
          props_ = new java.util.ArrayList<VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2>(props_);
          bitField0_ |= 0x00000100;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2OrBuilder> propsBuilder_;

      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public java.util.List<VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2> getPropsList() {
        if (propsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(props_);
        } else {
          return propsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public int getPropsCount() {
        if (propsBuilder_ == null) {
          return props_.size();
        } else {
          return propsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 getProps(int index) {
        if (propsBuilder_ == null) {
          return props_.get(index);
        } else {
          return propsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public Builder setProps(
          int index, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 value) {
        if (propsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropsIsMutable();
          props_.set(index, value);
          onChanged();
        } else {
          propsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public Builder setProps(
          int index, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder builderForValue) {
        if (propsBuilder_ == null) {
          ensurePropsIsMutable();
          props_.set(index, builderForValue.build());
          onChanged();
        } else {
          propsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public Builder addProps(VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 value) {
        if (propsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropsIsMutable();
          props_.add(value);
          onChanged();
        } else {
          propsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public Builder addProps(
          int index, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2 value) {
        if (propsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePropsIsMutable();
          props_.add(index, value);
          onChanged();
        } else {
          propsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public Builder addProps(
          VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder builderForValue) {
        if (propsBuilder_ == null) {
          ensurePropsIsMutable();
          props_.add(builderForValue.build());
          onChanged();
        } else {
          propsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public Builder addProps(
          int index, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder builderForValue) {
        if (propsBuilder_ == null) {
          ensurePropsIsMutable();
          props_.add(index, builderForValue.build());
          onChanged();
        } else {
          propsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public Builder addAllProps(
          java.lang.Iterable<? extends VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2> values) {
        if (propsBuilder_ == null) {
          ensurePropsIsMutable();
          super.addAll(values, props_);
          onChanged();
        } else {
          propsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public Builder clearProps() {
        if (propsBuilder_ == null) {
          props_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000100);
          onChanged();
        } else {
          propsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public Builder removeProps(int index) {
        if (propsBuilder_ == null) {
          ensurePropsIsMutable();
          props_.remove(index);
          onChanged();
        } else {
          propsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder getPropsBuilder(
          int index) {
        return getPropsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2OrBuilder getPropsOrBuilder(
          int index) {
        if (propsBuilder_ == null) {
          return props_.get(index);  } else {
          return propsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public java.util.List<? extends VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2OrBuilder> 
           getPropsOrBuilderList() {
        if (propsBuilder_ != null) {
          return propsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(props_);
        }
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder addPropsBuilder() {
        return getPropsFieldBuilder().addBuilder(
            VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.getDefaultInstance());
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder addPropsBuilder(
          int index) {
        return getPropsFieldBuilder().addBuilder(
            index, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.getDefaultInstance());
      }
      /**
       * <code>repeated .VO_Esse_Detail2.VO_Esse_Prop_Detail2 props = 9;</code>
       *
       * <pre>
       *技能信息
       * </pre>
       */
      public java.util.List<VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder> 
           getPropsBuilderList() {
        return getPropsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2OrBuilder> 
          getPropsFieldBuilder() {
        if (propsBuilder_ == null) {
          propsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2.Builder, VO_Esse_Detail2Entity.VO_Esse_Detail2.VO_Esse_Prop_Detail2OrBuilder>(
                  props_,
                  ((bitField0_ & 0x00000100) == 0x00000100),
                  getParentForChildren(),
                  isClean());
          props_ = null;
        }
        return propsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:VO_Esse_Detail2)
    }

    static {
      defaultInstance = new VO_Esse_Detail2(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:VO_Esse_Detail2)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_VO_Esse_Detail2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VO_Esse_Detail2_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_VO_Esse_Detail2_VO_Esse_Prop_Detail2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VO_Esse_Detail2_VO_Esse_Prop_Detail2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025VO_Esse_Detail2.proto\"\376\001\n\017VO_Esse_Deta" +
      "il2\022\013\n\003rid\030\001 \002(\005\022\n\n\002lv\030\002 \002(\005\022\013\n\003exp\030\003 \002(" +
      "\003\022\017\n\007quality\030\004 \002(\005\022\022\n\nthrounghLv\030\005 \002(\005\022\014" +
      "\n\004slot\030\006 \002(\005\022\021\n\tfromation\030\007 \002(\005\022\014\n\004body\030" +
      "\010 \001(\014\0224\n\005props\030\t \003(\0132%.VO_Esse_Detail2.V" +
      "O_Esse_Prop_Detail2\032;\n\024VO_Esse_Prop_Deta" +
      "il2\022\020\n\010propType\030\001 \002(\005\022\021\n\tpropValue\030\002 \002(\005" +
      "B\027B\025VO_Esse_Detail2Entity"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_VO_Esse_Detail2_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_VO_Esse_Detail2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_VO_Esse_Detail2_descriptor,
              new java.lang.String[] { "Rid", "Lv", "Exp", "Quality", "ThrounghLv", "Slot", "Fromation", "Body", "Props", });
          internal_static_VO_Esse_Detail2_VO_Esse_Prop_Detail2_descriptor =
            internal_static_VO_Esse_Detail2_descriptor.getNestedTypes().get(0);
          internal_static_VO_Esse_Detail2_VO_Esse_Prop_Detail2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_VO_Esse_Detail2_VO_Esse_Prop_Detail2_descriptor,
              new java.lang.String[] { "PropType", "PropValue", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
